apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rclone-example
  annotations:
    csi-rclone/storage-path: nginx
    csi-rclone/umask: "022"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-example
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data-rclone-example
  volumes:
  - name: data-rclone-example
    persistentVolumeClaim:
      claimName: data-rclone-example
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-example
